import type { Package, PackageSize } from "./types";

type Seed = {
  trackingNumber: string;
  recipient: string;
  deliveryAddress: string;
  stopNumber: number;
  size: PackageSize;
  weight: number;
  fragile: boolean;
};

const seeds: Seed[] = [
  {
    trackingNumber: "PF104829316701",
    recipient: "Maya Chen",
    deliveryAddress: "1842 Main Street, Fredericton North, NB E3A 1K4",
    stopNumber: 1,
    size: "medium",
    weight: 8.4,
    fragile: false,
  },
  {
    trackingNumber: "PF104829316718",
    recipient: "Luis Ortega",
    deliveryAddress: "615 Smythe Street, Fredericton North, NB E3A 2H8",
    stopNumber: 2,
    size: "large",
    weight: 36.2,
    fragile: false,
  },
  {
    trackingNumber: "PF218847190044",
    recipient: "Luis Ortega",
    deliveryAddress: "615 Smythe Street, Fredericton North, NB E3A 2H8",
    stopNumber: 2,
    size: "small",
    weight: 2.4,
    fragile: true,
  },
  {
    trackingNumber: "PF330192884615",
    recipient: "Priya Shah",
    deliveryAddress: "90 Prospect Street, Fredericton North, NB E3A 3N2",
    stopNumber: 3,
    size: "medium",
    weight: 11,
    fragile: false,
  },
  {
    trackingNumber: "PF330192884622",
    recipient: "River Desk Co.",
    deliveryAddress: "418 Queen Street, Downtown Fredericton, NB E3B 1A7",
    stopNumber: 4,
    size: "medium",
    weight: 15.6,
    fragile: false,
  },
  {
    trackingNumber: "PF441908773150",
    recipient: "River Desk Co.",
    deliveryAddress: "418 Queen Street, Downtown Fredericton, NB E3B 1A7",
    stopNumber: 4,
    size: "small",
    weight: 3.1,
    fragile: true,
  },
  {
    trackingNumber: "PF441908773167",
    recipient: "Jonah Hale",
    deliveryAddress: "726 King Street, Downtown Fredericton, NB E3B 1E5",
    stopNumber: 5,
    size: "large",
    weight: 41,
    fragile: false,
  },
  {
    trackingNumber: "PF552671004983",
    recipient: "Jonah Hale",
    deliveryAddress: "726 King Street, Downtown Fredericton, NB E3B 1E5",
    stopNumber: 5,
    size: "small",
    weight: 4.8,
    fragile: false,
  },
  {
    trackingNumber: "PF663820119447",
    recipient: "Amina Diallo",
    deliveryAddress: "1408 Regent Street, University area, Fredericton, NB E3B 4M6",
    stopNumber: 6,
    size: "medium",
    weight: 12.5,
    fragile: false,
  },
  {
    trackingNumber: "PF663820119454",
    recipient: "Harper Quinn",
    deliveryAddress: "55 Prospect Street, Unit 6C, University area, Fredericton, NB E3B 5R1",
    stopNumber: 7,
    size: "medium",
    weight: 9.2,
    fragile: true,
  },
  {
    trackingNumber: "PF774019338261",
    recipient: "Harper Quinn",
    deliveryAddress: "55 Prospect Street, Unit 6C, University area, Fredericton, NB E3B 5R1",
    stopNumber: 7,
    size: "large",
    weight: 28.7,
    fragile: false,
  },
  {
    trackingNumber: "PF885192447018",
    recipient: "Queen Kettle Cafe",
    deliveryAddress: "880 Queen Street, Downtown Fredericton, NB E3B 1G4",
    stopNumber: 8,
    size: "small",
    weight: 5.5,
    fragile: false,
  },
  {
    trackingNumber: "PF885192447025",
    recipient: "Rosa Bennett",
    deliveryAddress: "1204 Main Street, Southside, Fredericton, NB E3B 6P3",
    stopNumber: 9,
    size: "medium",
    weight: 18.4,
    fragile: false,
  },
  {
    trackingNumber: "PF901772650334",
    recipient: "Rosa Bennett",
    deliveryAddress: "1204 Main Street, Southside, Fredericton, NB E3B 6P3",
    stopNumber: 9,
    size: "small",
    weight: 2.2,
    fragile: true,
  },
  {
    trackingNumber: "PF901772650341",
    recipient: "Kenji Watanabe",
    deliveryAddress: "47 King Street, Southside, Fredericton, NB E3B 3T9",
    stopNumber: 10,
    size: "large",
    weight: 33,
    fragile: false,
  },
  {
    trackingNumber: "PF112640883907",
    recipient: "Kenji Watanabe",
    deliveryAddress: "47 King Street, Southside, Fredericton, NB E3B 3T9",
    stopNumber: 10,
    size: "medium",
    weight: 7.8,
    fragile: false,
  },
  {
    trackingNumber: "PF223751994018",
    recipient: "Samira Haddad",
    deliveryAddress: "915 Prospect Street, Uptown Fredericton, NB E3B 7L5",
    stopNumber: 11,
    size: "small",
    weight: 3.6,
    fragile: true,
  },
  {
    trackingNumber: "PF334862105129",
    recipient: "Samira Haddad",
    deliveryAddress: "915 Prospect Street, Uptown Fredericton, NB E3B 7L5",
    stopNumber: 11,
    size: "medium",
    weight: 14.1,
    fragile: false,
  },
  {
    trackingNumber: "PF334862105136",
    recipient: "Owen Briggs",
    deliveryAddress: "308 Smythe Street, Uptown Fredericton, NB E3C 1A4",
    stopNumber: 12,
    size: "large",
    weight: 39.5,
    fragile: false,
  },
  {
    trackingNumber: "PF445973216240",
    recipient: "Lila Nguyen",
    deliveryAddress: "672 Regent Street, Uptown Fredericton, NB E3C 2N8",
    stopNumber: 13,
    size: "medium",
    weight: 10.4,
    fragile: false,
  },
  {
    trackingNumber: "PF556084327351",
    recipient: "Lila Nguyen",
    deliveryAddress: "672 Regent Street, Uptown Fredericton, NB E3C 2N8",
    stopNumber: 13,
    size: "small",
    weight: 1.8,
    fragile: true,
  },
  {
    trackingNumber: "PF667195438462",
    recipient: "Prospect Page Books",
    deliveryAddress: "41 Prospect Street, Hanwell area, Fredericton, NB E3C 3R6",
    stopNumber: 14,
    size: "medium",
    weight: 16.9,
    fragile: false,
  },
  {
    trackingNumber: "PF778206549573",
    recipient: "Andre Brooks",
    deliveryAddress: "1550 Main Street, Hanwell area, Fredericton, NB E3C 4W1",
    stopNumber: 15,
    size: "small",
    weight: 6.1,
    fragile: false,
  },
  {
    trackingNumber: "PF889317650684",
    recipient: "Andre Brooks",
    deliveryAddress: "1550 Main Street, Hanwell area, Fredericton, NB E3C 4W1",
    stopNumber: 15,
    size: "large",
    weight: 27.3,
    fragile: true,
  },
  {
    trackingNumber: "PF990428761795",
    recipient: "Camille Ortiz",
    deliveryAddress: "220 King Street, Hanwell area, Fredericton, NB E3C 1H7",
    stopNumber: 16,
    size: "medium",
    weight: 13.2,
    fragile: false,
  },
  {
    trackingNumber: "PF101539872806",
    recipient: "Theo Marshall",
    deliveryAddress: "814 Smythe Street, Hanwell area, Fredericton, NB E3C 2B3",
    stopNumber: 17,
    size: "large",
    weight: 44,
    fragile: false,
  },
  {
    trackingNumber: "PF212640983917",
    recipient: "Theo Marshall",
    deliveryAddress: "814 Smythe Street, Hanwell area, Fredericton, NB E3C 2B3",
    stopNumber: 17,
    size: "small",
    weight: 2.9,
    fragile: true,
  },
  {
    trackingNumber: "PF323751094028",
    recipient: "Nina Petrov",
    deliveryAddress: "19 Queen Street, Hanwell area, Fredericton, NB E3C 5K2",
    stopNumber: 18,
    size: "medium",
    weight: 8.7,
    fragile: false,
  },
  {
    trackingNumber: "PF434862105139",
    recipient: "Hanwell Dental Studio",
    deliveryAddress: "460 Prospect Street, Hanwell area, Fredericton, NB E3C 1M9",
    stopNumber: 19,
    size: "small",
    weight: 4.4,
    fragile: true,
  },
  {
    trackingNumber: "PF545973216240",
    recipient: "Marcus Webb",
    deliveryAddress: "2777 Main Street, Hanwell area, Fredericton, NB E3C 4A8",
    stopNumber: 20,
    size: "medium",
    weight: 19.6,
    fragile: false,
  },
];

export const mockPackages: Package[] = seeds.map((seed, index) => ({
  id: `pkg-${String(index + 1).padStart(2, "0")}`,
  ...seed,
  zone: null,
  shelf: null,
  slot: null,
  status: "pending",
}));
